#!/bin/bash
echo "atsm: sending message" >> /tmp/log.log
curl 'https://api.twilio.com/2010-04-01/Accounts/API_KEY/Messages.json' -X POST \
--data-urlencode "To=+1$1" \
--data-urlencode 'From=+14125009503 ' \
--data-urlencode "Body=$2" \
-u API_KEY:AUTH_KEY
